version: '3.8'

services:
  hardcover-ai-librarian:

    image: dukkokun/hardcover-ai-librarian:latest
      
    ports:
      - "8501:8501"
    
    # Choose how to get the secrets and uncomment either options:

    # 1. OPTIONAL: Secrets File
    
    #volumes:
    #  - ./.streamlit/secrets.toml:/app/.streamlit/secrets.toml:ro

    # 2. OPTIONAL: Environment Variables
    
    #environment:
    #  - STREAMLIT_SECRETS_CONNECTIONS_HARDCOVER_TOKEN=${HARDCOVER_TOKEN}
    #  - STREAMLIT_SECRETS_CONNECTIONS_GEMINI_KEY=${GEMINI_KEY}
    #  - STREAMLIT_SECRETS_CONNECTIONS_OPENAI_KEY=${OPENAI_KEY}
    #  - STREAMLIT_SECRETS_CONNECTIONS_ANTHROPIC_KEY=${ANTHROPIC_KEY}
    
    # Restart automatically if it crashes
    restart: unless-stopped
    
    # Clean container name
    container_name: hardcover-ai-librarian